In [ ]:
#Import the necessary files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Read the dataset
df= pd.read_csv('ModeChoiceOptima.txt', sep='\t')

In [ ]:
#To check the format of the dataset
df.head()

,ID,DestAct,NbTransf,TimePT,WalkingTimePT,WaitingTimePT,CostPT,CostCar,TimeCar,NbHousehold,...,FreqTripHouseh,Region,distance_km,Choice,InVehicleTime,ModeToSchool,ReportedDuration,CoderegionCAR,age,Weight
0,10350017,2,4,85,23,10,12.4,3.17,32,2,...,4,1,30.0,1,52,3,255,1,27,0.000379
1,10350020,1,4,108,26,16,12.4,3.28,30,2,...,4,1,32.0,-1,66,3,150,1,28,0.000341
2,10350025,11,2,82,33,5,3.0,0.45,6,-1,...,2,1,4.5,0,44,-1,20,1,-1,0.000368
3,10350075,1,3,107,21,31,24.0,2.36,23,2,...,1,1,25.0,1,55,-1,30,1,63,0.000368
4,10350085,1,5,190,116,18,10.8,1.16,14,3,...,3,1,12.5,1,56,-1,20,1,57,0.000409

In [17]:
#Copy the dataframe
df1=df.copy()

In [18]:
df1.count()

ID                  2265
DestAct             2265
NbTransf            2265
TimePT              2265
WalkingTimePT       2265
                    ...
ModeToSchool        2265
ReportedDuration    2265
CoderegionCAR       2265
age                 2265
Weight              2265
Length: 117, dtype: int64

In [21]:
#Keeping all the values across the columns except -2
df1 = df1[(df1 != -2).all(axis=1)]
#Checking the count of entries in the dataset after removing the -2 values
df1.count()

ID                  2221
DestAct             2221
NbTransf            2221
TimePT              2221
WalkingTimePT       2221
                    ...
ModeToSchool        2221
ReportedDuration    2221
CoderegionCAR       2221
age                 2221
Weight              2221
Length: 117, dtype: int64

In [23]:
#Checking the count of entries in the Choice column with -1 values
df1[df1['Choice'] == -1].count()

ID                  350
DestAct             350
NbTransf            350
TimePT              350
WalkingTimePT       350
                   ...
ModeToSchool        350
ReportedDuration    350
CoderegionCAR       350
age                 350
Weight              350
Length: 117, dtype: int64

In [ ]:
#Drop the rows with -1 values in the Choice column
df1.drop(df1[df1['Choice'] == -1].index, inplace=True)
#Checking the count of entries after removal of -1 in the Choice column
df1.count()

ID                  1871
DestAct             1871
NbTransf            1871
TimePT              1871
WalkingTimePT       1871
                    ...
ModeToSchool        1871
ReportedDuration    1871
CoderegionCAR       1871
age                 1871
Weight              1871
Length: 117, dtype: int64

In [ ]:
#Converting all the entries with (-1) values to NaN values in the dataset
df1.replace(-1, np.nan, inplace=True)

,ID,DestAct,NbTransf,TimePT,WalkingTimePT,WaitingTimePT,CostPT,CostCar,TimeCar,NbHousehold,...,FreqTripHouseh,Region,distance_km,Choice,InVehicleTime,ModeToSchool,ReportedDuration,CoderegionCAR,age,Weight
0,10350017,2.0,4,85,23,10,12.4,3.17,32,2.0,...,4.0,1,30.0,1,52.0,3.0,255.0,1,27.0,0.000379
3,10350075,1.0,3,107,21,31,24.0,2.36,23,2.0,...,1.0,1,25.0,1,55.0,NaN,30.0,1,63.0,0.000368
4,10350085,1.0,5,190,116,18,10.8,1.16,14,3.0,...,3.0,1,12.5,1,56.0,NaN,20.0,1,57.0,0.000409
5,10350086,1.0,4,116,38,29,9.6,1.89,20,3.0,...,3.0,1,19.0,1,49.0,NaN,30.0,1,58.0,0.000368
6,10350100,4.0,1,20,1,5,3.0,1.14,9,1.0,...,1.0,1,13.0,1,14.0,4.0,10.0,1,80.0,0.000202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2259,96040531,1.0,4,148,28,69,10.4,3.92,40,5.0,...,3.0,7,42.0,1,51.0,5.0,35.0,7,37.0,0.000870
2261,96040537,8.0,0,139,116,0,14.4,3.18,43,5.0,...,3.0,7,32.0,1,23.0,5.0,70.0,7,46.0,0.000368
2262,96040537,8.0,0,71,57,0,6.0,0.94,12,5.0,...,3.0,7,9.0,1,14.0,5.0,20.0,7,46.0,0.000368
2263,96040538,11.0,2,118,70,10,11.4,1.77,24,5.0,...,4.0,7,17.5,1,38.0,3.0,30.0,7,49.0,0.000409
2264,96040538,1.0,3,140,53,23,12.6,2.23,28,5.0,...,4.0,7,20.0,1,64.0,3.0,40.0,7,49.0,0.000409

In [26]:
df1['YearsInHouse'].value_counts()

YearsInHouse
2.0     121
10.0    116
3.0     116
5.0     115
1.0      89
       ...
71.0      1
51.0      1
69.0      1
61.0      1
56.0      1
Name: count, Length: 61, dtype: int64

In [27]:
#Filling the NaN values with the mode of the respective columns
for col in df1.columns:
    mode_val = df1[col].mode()
    if not mode_val.empty:
        df1[col].fillna(mode_val[0], inplace=True)

C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)
C:\conda_temp\ipykernel_10632\1002379674.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1[col].fillna(mode_val[0], inplace=True)

In [31]:
#Checking the count of entries in the dataset after filling the NaN values with mode of respective columns
df1.head(10)

,ID,DestAct,NbTransf,TimePT,WalkingTimePT,WaitingTimePT,CostPT,CostCar,TimeCar,NbHousehold,...,FreqTripHouseh,Region,distance_km,Choice,InVehicleTime,ModeToSchool,ReportedDuration,CoderegionCAR,age,Weight
0,10350017,2.0,4,85,23,10,12.4,3.17,32,2.0,...,4.0,1,30.0,1,52.0,3.0,255.0,1,27.0,0.000379
3,10350075,1.0,3,107,21,31,24.0,2.36,23,2.0,...,1.0,1,25.0,1,55.0,NaN,30.0,1,63.0,0.000368
4,10350085,1.0,5,190,116,18,10.8,1.16,14,3.0,...,3.0,1,12.5,1,56.0,NaN,20.0,1,57.0,0.000409
5,10350086,1.0,4,116,38,29,9.6,1.89,20,3.0,...,3.0,1,19.0,1,49.0,NaN,30.0,1,58.0,0.000368
6,10350100,4.0,1,20,1,5,3.0,1.14,9,1.0,...,1.0,1,13.0,1,14.0,4.0,10.0,1,80.0,0.000202
10,10350120,4.0,4,116,26,34,24.8,4.87,33,2.0,...,3.0,1,45.0,1,56.0,5.0,30.0,1,64.0,0.000098
11,10350125,4.0,1,35,15,4,4.8,0.69,9,1.0,...,3.0,1,7.0,1,16.0,4.0,15.0,1,68.0,0.000289
12,10350125,11.0,0,11,10,0,2.2,0.13,1,1.0,...,3.0,1,1.0,1,1.0,4.0,7.0,1,68.0,0.000289
13,10350133,1.0,3,92,35,8,11.0,2.71,27,2.0,...,4.0,1,27.0,1,49.0,4.0,60.0,1,59.0,0.000409
14,10350197,1.0,5,124,36,24,11.0,2.44,22,2.0,...,3.0,1,26.0,1,64.0,1.0,24.0,1,30.0,0.000379

In [32]:
#Saving the cleaned dataset to a new CSV file
df1.to_csv('Cleaned_Dataset_Updated.csv', index=False)

In [35]:
#Summary statistics of the cleaned dataset
df1_stat=df1.describe()

In [36]:
#Saving the summary statistics of the cleaned dataset to a new CSV file
df1_stat.to_csv('Summary_Statistics_Cleaned_Dataset_Updated.csv', index=True)